FROM ubuntu:14.04
MAINTAINER Jerry Wardlow <jerry@jerryoftheyear.com>

RUN apt-get update && apt-get install -y \ 
                              curl \
                              git \
                              tar \
                              vim \
                              wget
