---

web:
    image: jerrywardlow/vanilla
    links:
        - db:database
    ports:
        - "6680:80"

db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: secretpasword
        MYSQL_DATABASE: vanilladb
