---

web:
    build: .
    image: vanilla
    ports:
        - "6680:80"
    depends_on:
        - db:database

db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: secretpasword
        MYSQL_DATABASE: vanilladb
