---
- hosts: 127.0.0.1
  user: root
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
    with_items:
        - apache2
        - git
