version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scraper
      MYSQL_USER: scraper
      MYSQL_PASSWORD: scraper

volumes:
  db_data:
