version: '3.0'
services:
  chrome:
    image: jess/chrome
    container_name: chrome-x11
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: "unix${DISPLAY}"
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
