version: '3'

services:
  blog:
    build: ./blog
    image: haproxy-blog:latest
    expose:
      - "80"

  shop:
    build: ./shop
    image: haproxy-shop:latest
    expose:
      - "80"

  lb:
    build: ./lb
    image: haproxy-lb:latests
    depends_on:
      - blog
      - shop
