version: '3'

services:
  blog:
    build: ./blog
    image: haproxy-blog:latest
    restart: always
    expose:
      - "80"

  shop:
    build: ./shop
    image: haproxy-shop:latest
    restart: always
    expose:
      - "80"

  lb:
    build: ./lb
    image: haproxy-lb:latest
    restart: always
    networks:
      default:
        ipv4_address: 172.168.56.78
    depends_on:
      - blog
      - shop
    links:
      - blog
      - shop

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.168.56.0/24
